# Generated by Django 5.0.7 on 2024-08-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_alter_buyer_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits='100', null=True),
        ),
    ]
