# Generated by Django 4.2.11 on 2024-08-06 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0003_game_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=100),
        ),
    ]
