# Generated by Django 5.0.7 on 2024-08-06 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0004_alter_game_description_alter_game_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='buyer',
            field=models.ManyToManyField(to='task1.buyer'),
        ),
    ]
