# Generated by Django 4.2.11 on 2024-08-06 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0004_alter_game_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cost',
            field=models.CharField(max_length=100),
        ),
    ]
