# Generated by Django 4.2.11 on 2024-08-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0005_alter_game_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
