# Generated by Django 4.2.11 on 2024-08-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0006_alter_game_cost_alter_game_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
