# Generated by Django 4.2.11 on 2024-08-08 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0007_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
        migrations.AddField(
            model_name='buyer',
            name='password',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
